from controllers.one_three_eight import OneThreeEightController
from controllers.upc import UpcController
from controllers.three_nine import ThreeNineController
from controllers.issn import IssnController
from controllers.isbn_ten import IsbnTenController
from controllers.isbn_one_three import IsbnOneThreeController